### PR TITLE
Fix default style for labels and inputs

### PR DESCRIPTION
**Pull request by cleicar**
This PR includes a small change to make labels and inputs to be gray by default.

Pivotal Tracker: https://www.pivotaltracker.com/n/projects/2237246/stories/174780812

PS: we need to update ombulabs styleguide reference after merging this.

### CODE REVIEW

**Review by arielj — CHANGES_REQUESTED** [review]
I'm testing this in an empty new rails project (just did rails new, added the styleguide and a view with a form with two labels, a text input and a text area) and everything is white.

I understand you added the default color for the border of the input and textarea but only if those are inside a form with class `new_contact`, but the default color is still white for a clean form tag. Same with the labels, are white by default and grey only if the parent form has a `new_contact` class.

**Comment by arielj** [comment]
I think the issue is this style https://github.com/ombulabs/styleguide/blob/02548d6a3b7f733088c53f279efdd0e51e76ae1d/vendor/assets/stylesheets/ombulabs/styleguide/3-atoms/_forms.scss#L4

**Review by arielj — CHANGES_REQUESTED** [review]
Hey, now I can see the label but the input/textearea still all white by default, default border is white here https://github.com/ombulabs/styleguide/blob/df48fc6ec6447936b671ec54c24f66baa2c58c69/vendor/assets/stylesheets/ombulabs/styleguide/3-atoms/_forms.scss#L21 (also a few lines above it has a `border: none`, we can remove that too)

**Comment by etagwerker** [comment]
@cleicar Did you get a chance to see Ariel's comments?

**Review by arielj — APPROVED** [review]

**Comment by arielj** [comment]
I deployed this to staging and this is the only place were we use the inputs at ombulabs and it looks the same so that's good. https://ombulabs-staging.herokuapp.com/contact

I created a simple rails new app, added the styleguide and added a simple form tag and now it's visible by default.

I'm not sure if this requires QA since it's not something that affects a concrete website but just a generic optimization. @ABizzinotto

**Comment by arielj** [comment]
Also @cleicar, I guess we should update the static files after changing CSS so the compiled files include the new css.

**Review by ABizzinotto — APPROVED** [review]
Looks good. Ready to merge!

**Pull request merged**
