### PR TITLE
Fix margin for testimonial carousel. 

### PR DESCRIPTION
**Pull request by FionaDL**
This PR is for https://www.pivotaltracker.com/story/show/172178976

We changed the margin to left in the styleguide for extra-small so that it won't overlap with the text. I worked on this with @lubc

### CODE REVIEW

**Review by arielj — APPROVED** [review]
Looks good, I'm not a friend of negative margins, but it's a quick solution for a really small issue.

Adding a screenshot to show how it looks now:
localhost_3000_(iPhone X) (1)

**Comment by arielj** [comment]
This is ready for QA https://ombulabs-staging.herokuapp.com

**Review by etagwerker — CHANGES_REQUESTED** [review]
@FionaDL I don't think it is a good idea to move the title to the left. It makes it look misaligned compared to all the other titles. 

Screen Shot 2020-09-10 at 11 48 45 PM

I would like to see a solution that keeps the title centered and moves the arrows down a little. Something like this but with more space between title, arrows, and quotes: 

Screen Shot 2020-09-10 at 11 48 30 PM

It seems that the current implementation relies in a before block of guidelines which is very weird: 

Screen Shot 2020-09-10 at 11 49 12 PM
Screen Shot 2020-09-10 at 11 49 17 PM

This is not the best implementation for margins/paddings. I would like to see a solution that gets right of that ::before block of code and it follows a more simple implementation (something with margin, padding maybe?)

**Comment by FionaDL** [comment]
@etagwerker sounds good. The arrows have been moved below and to the right. I also removed the before block in this PR:
https://github.com/ombulabs/ombulabs.com/pull/209

**Review by etagwerker — APPROVED** [review]
@FionaDL Looks good, thanks! 👍

**Comment by etagwerker** [comment]
@ABizzinotto Just deployed this PR + ombulabs/ombulabs.com#209 to staging. Please take a few minutes to QA these changes and test with different devices. Thanks!

**Comment by ABizzinotto** [comment]
@FionaDL @etagwerker looks good. However, the arrows look a tad weird on mobile devices.

This is what I have on Android:

tempFileForShare_20200914-165456

Arrow looks the same on iOS and it also gets black when I tap it:

File

Not sure if you'd rather handle this separately or here though

**Comment by FionaDL** [comment]
@ABizzinotto I wonder if we should create a separate story for this, I just checked what is in production and it looks like it is happening there as well. 
Made a story here: https://www.pivotaltracker.com/story/show/174808972

**Pull request merged**
